// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Sideas.Challenge.Infrastructure.Data;

#nullable disable

namespace Sideas.Challenge.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250724233806_iunicial")]
    partial class iunicial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Sideas.Challenge.Domain.Entities.Agrupacion", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Agrupaciones");
                });

            modelBuilder.Entity("Sideas.Challenge.Domain.Entities.AgrupacionProfesion", b =>
                {
                    b.Property<int>("AgrupacionId")
                        .HasColumnType("int");

                    b.Property<int>("ProfesionId")
                        .HasColumnType("int");

                    b.HasKey("AgrupacionId", "ProfesionId");

                    b.HasIndex("ProfesionId");

                    b.ToTable("AgrupacionProfesiones");
                });

            modelBuilder.Entity("Sideas.Challenge.Domain.Entities.Asignacion", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<int?>("AnioExp")
                        .HasColumnType("int");

                    b.Property<string>("Autos")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreacionFecha")
                        .HasColumnType("datetime2");

                    b.Property<long?>("DocAuxiliar")
                        .HasColumnType("bigint");

                    b.Property<string>("EspecialidadAuxiliar")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Fuero")
                        .HasColumnType("int");

                    b.Property<int?>("IdProfesionAux")
                        .HasColumnType("int");

                    b.Property<int?>("Incidente")
                        .HasColumnType("int");

                    b.Property<string>("NombreAuxiliar")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NumeroExp")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProfesionAuxiliar")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Reparticion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TipoDocAuxiliar")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Zona")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Asignaciones");
                });

            modelBuilder.Entity("Sideas.Challenge.Domain.Entities.Fuero", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Fueros");
                });

            modelBuilder.Entity("Sideas.Challenge.Domain.Entities.Profesion", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Especialidad")
                        .HasColumnType("int");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProfesionCodigo")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Profesiones");
                });

            modelBuilder.Entity("Sideas.Challenge.Domain.Entities.Zona", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("FueroId")
                        .HasColumnType("int");

                    b.Property<string>("Reparticion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Zonas");
                });

            modelBuilder.Entity("Sideas.Challenge.Domain.Entities.AgrupacionProfesion", b =>
                {
                    b.HasOne("Sideas.Challenge.Domain.Entities.Agrupacion", "Agrupacion")
                        .WithMany("AgrupacionProfesiones")
                        .HasForeignKey("AgrupacionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Sideas.Challenge.Domain.Entities.Profesion", "Profesion")
                        .WithMany("AgrupacionProfesiones")
                        .HasForeignKey("ProfesionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Agrupacion");

                    b.Navigation("Profesion");
                });

            modelBuilder.Entity("Sideas.Challenge.Domain.Entities.Agrupacion", b =>
                {
                    b.Navigation("AgrupacionProfesiones");
                });

            modelBuilder.Entity("Sideas.Challenge.Domain.Entities.Profesion", b =>
                {
                    b.Navigation("AgrupacionProfesiones");
                });
#pragma warning restore 612, 618
        }
    }
}
